import "~/styles/globals.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "../trpc/react";
import { ThemeProvider } from "next-themes";
import React from "react";
import Nav from "./_components/components/ui/Nav";
import ParticleBackground from "./_components/components/animations/ParticleBackground";

export const metadata: Metadata = {
  title: "Stonx WebApp",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.png" }],
};
// className={`${GeistSans.variable}`}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" >
      <body className="fontfamily-sans overflow-x-clip  ">
        {/* <div className="h-dvh flex flex-col  backdrop-blur-[100px] bg-black/10 "> */}
        <ThemeProvider attribute="class" defaultTheme="system" >
          <Nav />
          <ParticleBackground />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ThemeProvider>
        {/* </div> */}
      </body >
    </html >
  );
}
