import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
// className={`${GeistSans.variable}`}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" >
      <body className="fontfamily-sans overflow-x-hidden bg-gradient-to-br from-background to-secondary ">
        <div className="h-dvh  backdrop-blur-[100px] bg-black/10 ">
          <ThemeProvider attribute="class" defaultTheme="system" >
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </ThemeProvider>
        </div>
      </body >
    </html >
  );
}
