import "~/styles/globals.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "../trpc/react";
import { ThemeProvider } from "next-themes";
import React from "react";
import Nav from "./_components/components/ui/Nav";
import ParticleBackground from "./_components/components/animations/ParticleBackground";
import { StarsBackground } from "./_components/components/animations/StarsBackground";
import AnimatedBackground from "./_components/components/animations/bg-animation";

export const metadata: Metadata = {
  title: "Stonx WebApp",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.png" }],
};
// className={`${GeistSans.variable}`}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" >
      <body className="fontfamily-sans  overflow-x-hidden h-screen  ">
        <ThemeProvider attribute="class" defaultTheme="system" >
          <Nav />
          {/* <StarsBackground /> */}
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <AnimatedBackground />
        </ThemeProvider>
      </body >
    </html >
  );
}
